shopping-trifecta/graceshopper

- server/api/index.js
- server/api/order.js
- server/db/models/index.js
- server/db/models/lineItem.js
- server/db/models/order.js
> Order backend

- server/api/index.js
- server/api/products.js
- server/db/models/product.js
> Products backend

- server/api/categories.js
- server/api/index.js
> Finished category routes

- server/api/reviews.js
- server/api/users.js
- server/db/models/category.js
- server/db/models/review.js
- server/db/models/user.js
> Added Reviews & Categories and modified Users

- server/api/categories.js
- server/api/index.js
- server/api/orders.js
- server/api/products.js
- server/api/reviews.js
- server/api/users.js
- server/db/models/category.js
- server/db/models/index.js
- server/db/models/lineItem.js
- server/db/models/order.js
- server/db/models/product.js
- server/db/models/review.js
- server/db/models/user.js
> Associations

- package-lock.json
- package.json
- server/api/reviews.js
- server/api/users.js
- server/db/models/index.js
- server/db/models/review.js
> DB synced and tested

- server/db/models/order.js
> tweaked getter method

- utils.js
> utils file

- server/api/orders.js
- utils.js
> authentication added for orders

- server/api/categories.js
- server/api/reviews.js
> Auth lang in Categories and Reviews

- server/api/users.js
> added users auth lang

- script/seed.js
> partially completed seed file

- script/seed.js
> added comment for original seed order

- server/api/orders.js
- server/api/products.js
- server/db/models/lineItem.js
- server/db/models/lineItem.spec.js
- server/db/models/order.js
> makes v minor changes to backend products and orders

- client/components/Reviews.js
- client/store/allReviews.js
- client/store/currentReview.js
- client/store/index.js
- server/api/reviews.js
> Reviews redux

- client/app.js
- client/components/Cart.js
- client/components/SingleItem.js
- client/store/currentReview.js
- client/store/index.js
> began cart component

- client/store/allCategories.js
- client/store/allProducts.js
- client/store/singleCategory.js
- client/store/singleProduct.js
> adds reducers for allProdcuts, singleProduct, and allCategories

- client/store/allOrders.js
- client/store/order.js
- client/store/user.js
> Reducers for user and orders

- client/components/AllCategories.js
- client/components/AllProducts.js
- client/components/Reviews.js
- script/seed.js
> updates seed file, makes minor front end changes

- client/components/AllOrders.js
- client/components/SingleOrder.js
- public/style.css
- script/seed.js
> added dummy data to seed file for admin test

- client/components/AllUsers.js
- client/components/SingleProduct.js
- client/components/navbar.js
- server/api/categories.js
- server/api/orders.js
- server/api/products.js
- server/api/reviews.js
- server/api/users.js
- server/db/models/user.js
- server/index.js
> makes authentication updates

- client/components/Reviews.js
- client/components/SingleProduct.js
- server/db/models/order.js
> makes minor updates

- client/components/AllOrders.js
- client/components/AllUsers.js
- client/components/NewProduct.js
- client/components/SingleOrder.js
- client/components/user-edit.js
- client/components/user-home.js
- client/store/editUser.js
- public/style.css
- script/seed.js
> Refactor users orders

- script/seed.js
- server/db/models/product.js
changed the default imgUrl for products and a couple of hard-coded ones in the seed
> edited default imgUrl and some product urls

- client/components/Checkout.js
- client/components/CheckoutForm.js
- client/components/GuestCart.js
- client/components/SingleProduct.js
- client/components/UserCart.js
- client/store/allCartItems.js
- client/store/allOrders.js
- public/style.css
> can edit product quantities in cart and some styling

- client/components/SingleOrder.js
- client/components/SingleProduct.js
- public/style.css
> makes minor css changes to single product and single order

- client/components/AllCategories.js
- client/components/AllOrders.js
- client/components/AllProducts.js
- client/components/AllUsers.js
- client/components/user-home.js
- public/style.css
- script/seed.js
> css styling

- client/components/Checkout.js
- client/components/GuestCart.js
- client/components/NewCategory.js
- client/components/NewProduct.js
- client/components/UserCart.js
- client/components/navbar.js
- client/store/allCartItems.js
- public/style.css
> added styling for checkout and forms

- public/style.css
> further merge conflict fixes

- client/components/SingleProduct.js
> minor product styling

- client/components/NewReview.js
- client/components/SingleProduct.js
- client/components/navbar.js
- public/style.css
> small product styling

- client/app.js
- client/components/AllProducts.js
- client/components/CartDisplay.js
- client/components/Checkout.js
- client/components/CheckoutForm.js
- client/components/Reviews.js
- client/components/SingleCategory.js
- client/components/SingleProduct.js
- client/components/auth-form.js
- client/components/user-home.js
- client/store/allOrders.js
- public/style.css
- script/seed.js
> Styles for deploy

- public/style.css
> last change

- public/style.css
> fixed header h2

- public/style.css
> fixed nav width

- public/style.css
> small nav fix

- client/components/CartDisplay.js
- client/components/SingleProduct.js
- public/style.css
> moved add to cart and ternary

- client/components/CartDisplay.js
> fixed products length
